### ISSUE TITLE
429 Error

### ISSUE THREAD

**Issue by rakyp** [yGuy/chatgpt-mattermost-bot#11]
Initial run of the bot, returns nothing after questions are asked. 

Running with TRACE shows the following: 

`{"level":"ERROR","name":"bot-ws","msg":"(node:27143) UnhandledPromiseRejectionWarning: Error: Request failed with status code 429\n`

Unsure what is causing the 429 error as this is the first time attempting to run/use a specific AI token, so would not expect any rate limiting to have been hit?

**Comment by yGuy** [comment]
I don't think this is an issue with the bot implementation.

See https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests

If the bot runs into this issue, but you can successfully access the API at the same time with the same token, feel free to reopen. I have not heard of this issue, before.
