### ISSUE TITLE
Why is my server up and running, but there is no response to my message to the bot?

### ISSUE THREAD

**Issue by abbottTom** [yGuy/chatgpt-mattermost-bot#12]
logs

websocket connecting to ws://192.168.88.200/api/v4/websocket

**Comment by yGuy** [comment]
Closing this with no further input, feel free to reopen once you have more information. It works for everyone else, I guess, and without knowing the difference in the setup there is no way we can help without further information.

**Comment by abbottTom** [comment]
Thanks, I already know what's going on because my robot's name isn't 'chatgpt'!
