### ISSUE TITLE
The images that chatgpt puts are not seen in mattermost

### ISSUE THREAD

**Issue by NexusEFR** [yGuy/chatgpt-mattermost-bot#14]
You only see image error icons from imgur.com or a mini icon of a broken graphic. Is any bot configuration necessary? Bot as admin or as a team user?

**Comment by WantToLearnJapanese** [comment]
AFAIK, the problem is the difference between Markdown format what MM supports and ChatGPT outputs.

**Comment by NexusEFR** [comment]
> AFAIK the problem is the difference between the Markdown format that MM supports and ChatGPT outputs.
> 
> As a workaround, you could manually modify the broken syntax for image links.

Thanks for the clarification and the fast response, although I don't know how to make that manual change or where to make it to see the image. I have an MM instance through Omnibus in Ubuntu and the docker in a Nas/Qnap. Regards. 😃

**Comment by WantToLearnJapanese** [comment]
> > AFAIK the problem is the difference between the Markdown format that MM supports and ChatGPT outputs.
> 
> > 
> 
> > As a workaround, you could manually modify the broken syntax for image links.
> 
> 
> 
> Thanks for the clarification and the fast response, although I don't know how to make that manual change or where to make it to see the image. I have an MM instance through Omnibus in Ubuntu and the docker in a Nas/Qnap. Regards. 😃 

Are you not a channel moderator? I was able to edit what ChatGPT bot says.

**Comment by NexusEFR** [comment]
> > > AFAIK the problem is the difference between the Markdown format that MM supports and ChatGPT outputs.
> > 
> > 
> > > 
> > 
> > 
> > > As a workaround, you could manually modify the broken syntax for image links.
> > 
> > 
> > Thanks for the clarification and the fast response, although I don't know how to make that manual change or where to make it to see the image. I have an MM instance through Omnibus in Ubuntu and the docker in a Nas/Qnap. Regards. 😃
> 
> Are you not a channel moderator? I was able to edit what ChatGPT bot says.

Oh sorry, I didn't realize what you were referring to. It's true that as an admin, I can edit messages. But I see that the link format is the same as the ones used for GIFs, like this example. ![Off to work](https://thumbs.gfycat.com/WhiteOptimisticGrackle-size_restricted.gif) And if I follow the link Chatgpt provided, the image is not found on the web either. Here is an image that Chatgpt posted according to a request... ![Diagrama de la línea de ascensión al trono de los Reyes Católicos](https://upload.wikimedia.org/wikipedia/commons/7/70/Lausanne_Memorial_39_%28cropped%29.jpg)

**Comment by NexusEFR** [comment]
> > > > AFAIK the problem is the difference between the Markdown format that MM supports and ChatGPT outputs.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > As a workaround, you could manually modify the broken syntax for image links.
> > > 
> > > 
> > > Thanks for the clarification and the fast response, although I don't know how to make that manual change or where to make it to see the image. I have an MM instance through Omnibus in Ubuntu and the docker in a Nas/Qnap. Regards. 😃
> > 
> > 
> > Are you not a channel moderator? I was able to edit what ChatGPT bot says.
> 
> Oh sorry, I didn't realize what you were referring to. It's true that as an admin, I can edit messages. But I see that the link format is the same as the ones used for GIFs, like this example. ! [Off to work](https://thumbs.gfycat.com/ WhiteOptimisticGrackle-size_restricted.gif) And if I follow the link Chatgpt provided, the image is not found on the web either. Here is an image that Chatgpt posted according to a request... ![Diagrama de la línea de ascensión al trono de los Reyes Católicos](htt ps://upload.wikimedia.org/wikipedia/commons/7/70/Lausanne_Memorial_39_%28cropped%29.jpg)

There are spaces in the links to be able to show the link without github trying to compose the image and to be able to see the original link from the MM. It is understood?

**Comment by yGuy** [comment]
Well, then ChatGPT hallucinated an URL. This is quite common and not something we can fix, I guess. 
ChatGPT is instructed to respond with markdown, but you cannot force it to create proper URLs. I don't think this is a problem with the plugin, but rather ChatGPT's "knowledge".

If this doesn't help, please post the exact response (you can crank up the logging to get all the details) and if you can come up with a way to "fix" the urls, this could be done via some postprocessing in the plugin.

**Comment by yGuy** [comment]
I think this is working as expected:
![image](https://user-images.githubusercontent.com/2486305/231451343-bad6897b-27dc-4225-917d-03422ce071d4.png)

**Comment by NexusEFR** [comment]
Here is the image that chatgpt returns to a request for an image of a spine :

![image](https://user-images.githubusercontent.com/68002188/231716844-f427b46f-4546-44d2-bea3-59f251455359.png)

And this is the link it points to, if you follow it you can't see any image " https://i.imgur.com/ze6dJJU.png  ". I put the previous example using gifcat inside MM to compare the type of link used by MM and ChatGPT, the issue is that the image links returned by ChatGPT are not valid.

![image](https://user-images.githubusercontent.com/68002188/231717573-ea381086-98c1-414e-9e8b-15a6e3c91df9.png)


https://i.imgur.com/ze6dJJU.png

**Comment by yGuy** [comment]
Correct. the Fault is not with the plugin, but with ChatGPT or the image source (which may have been removed in the meantime). I don't think it's the job of the plugin to validate and (try to) fix the image url. That's why I closed the issue. It's not a bug in the plugin.
