### ISSUE TITLE
When bot replying there is no "writing" info 

### ISSUE THREAD

**Issue by david-strejc** [yGuy/chatgpt-mattermost-bot#16]
Is there a way for us to make bot reply with "chatgpt writing" as it takes longer time for bot to reply and it seems nothing is happening when it is replying to our prompt.

**Comment by yGuy** [comment]
I am aware of this and if you look at the code, I am actually calling a function that *should* trigger the typing indicator. It doesn't seem to work, though, and currently I have not time to debug this. Would appreciate if someone could check. It might help to just continuously post the event while we are waiting for the response. 
It might be just a bug in the way I am calling the method and the parameters. This is from the Mattermost API which is not *that* well documented...

**Comment by david-strejc** [comment]
> I am aware of this and if you look at the code, I am actually calling a function that _should_ trigger the typing indicator. It doesn't seem to work, though, and currently I have not time to debug this. Would appreciate if someone could check. It might help to just continuously post the event while we are waiting for the response. It might be just a bug in the way I am calling the method and the parameters. This is from the Mattermost API which is not _that_ well documented...

Where exactly is this line of code? I will for fun let ChatGPT try to repair it :-)) (but I will also ask our dev team to look at it and make a PR)

**Comment by yGuy** [comment]
https://github.com/yGuy/chatgpt-mattermost-bot/search?q=typing&type=code

**Comment by lyca-knight** [comment]
I added a little "Loading Emoji". I'm uncertain if this is the correct way to do this, and we wanted to find a nicer emoji, that's why I didn't share it :)

wsClient.userUpdateActiveStatus(true, true);
const loadPost = await client.createPost({
    message: process.env["LOADING_MESSAGE"],
    channel_id: post.channel_id,
    root_id: post.root_id || post.id,
});

so, you can add any emoji:
LOADING_MESSAGE: ":thinking_face:"

**Comment by yGuy** [comment]
I took the idea from @Thunderbottom and improved it a little so that it stays on the screen, while the bot is typing. You should see the regular mattermost typing indication, with the latest commit
