### ISSUE TITLE
loop in restart for docker

### ISSUE THREAD

**Issue by flyfox666** [yGuy/chatgpt-mattermost-bot#23]
![image](https://user-images.githubusercontent.com/121539277/233816991-70309ab5-7283-4d66-bc30-83b04a00ed61.png)

**Comment by yGuy** [comment]
"localhost" doesn't sound like the right URL for the mattermost instance. Definitely the wrong one from within the docker image. 
Add the two containers to the same network and use container networking and name resolution, instead.

**Comment by flyfox666** [comment]
HI, Thanks a lot.
