### ISSUE TITLE
retain message content when creating a thread

### ISSUE THREAD

**Issue by InterestingSoup** [yGuy/chatgpt-mattermost-bot#24]
I am not sure what changed in the code but initially I was able to create a thread to a message and mention @chatgpt and the bot was able to pull information from the original message. 

For example, I had an automation that forwarded emails to a Mattermost channel called ~emails . I would then hit 'reply' on a message that was sent to the ~email channel and mention @chatgpt to draft a response. The bot was able to draft an email response based on original message I was replying to. 

Would it be possible to get this functionality back?

**Comment by yGuy** [comment]
I am not aware of a change that fits the description. 
Needs a repro for further investigation.
