### ISSUE TITLE
Feature Request: Allow setting the TEMPERATURE via process.env

### ISSUE THREAD

**Issue by your-highness** [yGuy/chatgpt-mattermost-bot#34]
Herein used package `openai` allows to set the temperature of the model (see https://platform.openai.com/docs/api-reference/chat/create ). The user should be allowed to set this value to a float in `[0,2]`.

Working on this right now. Pull request will follow.

**Comment by your-highness** [comment]
🚀

**Comment by yGuy** [comment]
Thanks. 

Is '1' the default that was being used implicitly when you did not specify the code? In other words: will this change the behavior for those who have *not* specified the value?

**Comment by your-highness** [comment]
> Thanks.
> 
> Is '1' the default that was being used implicitly when you did not specify the code? In other words: will this change the behavior for those who have _not_ specified the value?

As stated in https://platform.openai.com/docs/api-reference/chat/create#chat/create-temperature the default is 1:
![image](https://github.com/yGuy/chatgpt-mattermost-bot/assets/1949888/ceeed139-02d5-41ea-9ab2-102bdfb97f98)

**Comment by your-highness** [comment]
Dear @yGuy ,

_Any idea when this feature will be released via docker ghcr?_

P.S.: Sorry for commenting on closed issue

**Comment by your-highness** [comment]
I see it's already publish via master tag on https://ghcr.io/yguy/chatgpt-mattermost-bot :smile:
