### ISSUE TITLE
Update README: List OpenAI Node.js Library as Dependency

### ISSUE THREAD

**Issue by your-highness** [yGuy/chatgpt-mattermost-bot#37]
Working on this. Pull request will follow

**Comment by yGuy** [comment]
Thanks for the PR.

What's the idea behind listing this dependency? I mean, we could also list node.js and more obviously the mattermost plugin sdk API and the other utilities we have in package.json.... What's so special about mentioning this method? Those who are interested will be able to read the package.json and find the references in the code. Is this a requirement of the OpenAI API license?

**Comment by your-highness** [comment]
You are right. I just thought it's good practice for beginners to engage in contributing the plugin (like me 😄 ). Fell free to tag this as a `wontfix`
