### ISSUE TITLE
How to implement for self-hosted user?

### ISSUE THREAD

**Issue by vincentpricex** [yGuy/chatgpt-mattermost-bot#43]
I see there is a documentation for docker users only. Is there a roadmap for self-hosted (ubuntu) users? Can anyone help on how to set it up?

**Comment by yGuy** [comment]
it's

`git clone`
`npm install`
`npm run start`

Works on any platform that runs node.js

That's all.

**Comment by vincentpricex** [comment]
I think you're confused, I asked for mattermost?

**Comment by yGuy** [comment]
OK, I think you are confused :-) as this forum is not about mattermost, but the ChatGPT plugin. And my instructions above apply to the plugin.

**Comment by yGuy** [comment]
I don't get it. This is a bot that can be used with Mattermost. You can run the bot with or without docker. There are no limitations on the way that you are running your Mattermost instance, but having a Mattermost instance up and running is a precondition for using the bot. There is no information in this forum on how to install Mattermost. That would not belong here. Just like you won't find information in the Mattermost forum on how to install Ubunutu or build your own PC.

**Comment by vincentpricex** [comment]
=) I'm not asking a question about how to install mattermost. I'm not asking a question about how to set up mattermost. I'm asking how to integrate the bot in this repo into mattermost, there is only information on docker in the narration. I hope it is understood.

**Comment by yGuy** [comment]
>  I hope it is understood.

No, I am sorry, it's not understood. 
That's the question I answered first. It will let you integrate the bot with any Mattermost instance, no matter how and where it is hosted and this does not involve docker at all. If you don't understand, I am sorry, I don't think I can help you. This is not a polished end-user product for those who don't now a little node.js and command line tools.

**Comment by vincentpricex** [comment]
I hope one day will get it.
