### ISSUE TITLE
 chatgpt-mattermost-bot direct message

### ISSUE THREAD

**Issue by hudra0** [yGuy/chatgpt-mattermost-bot#44]
Can the ChatGPT Mattermost bot be used in direct messages with other team members? When I use "@chatgpt" in a direct message, nothing happens.

I have added the bot to my team, and now I can directly message the bot or add it to a channel and use "@chatgpt" to trigger the bot. However, it does not work when I mention the bot in a direct message with someone else.

**Comment by yGuy** [comment]
AFAIK the bot technically acts like a regular user. And since you cannot have a user join a direct message, Mattermost won't allow the bot to participate in a direct message between two users. For this to work, the bot would have to be implemented as a plugin, not as a bot.

**Comment by hudra0** [comment]
This makes makes sense. Thanks for the clarification.

**Comment by chrisfromredfin** [comment]
You can have a direct message between three people, though. I use this a lot. Me, my co-worker, and chatgpt are all in a DM.
