### ISSUE TITLE
[Bug] Bot fails with HTTP 400 when a username uses special characters

### ISSUE THREAD

**Issue by yGuy** [yGuy/chatgpt-mattermost-bot#46]
It seems OpenAI has pretty strict rules for user names. 
We need to sanitize the names before sending them to OpenAI, so that it will accept the user names.

The bot fails when there is a "." in the user name, e.g.

**Comment by MichaelH201** [comment]
"message": "a.b' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'messages.1.name'",
