### ISSUE TITLE
Bot refuses to create images.

### ISSUE THREAD

**Issue by whiskthecat** [yGuy/chatgpt-mattermost-bot#47]
I have not explicitly disabled any of the plugins. "Exit" plugin works.
Whenever I ask for an image to be generated the bot refuses by stating that it can only respond via text.

**Comment by yGuy** [comment]
Thanks, indeed, there is a problem with the default plugin settings - you need to set the "plugin" environment variable.
See this issue: #48

**Comment by whiskthecat** [comment]
Hmm, now I get "Sorry, but it seems there was an error when using the plugin image-plugin"

**Comment by yGuy** [comment]
True, thanks. I can reproduce this on one installation, but not on another. For some reason MM complains that the channel_id is not provided when uploading the image to MM. No idea at this point, how that could be the case.
