### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by phyx3r** [yGuy/chatgpt-mattermost-bot#52]
I've followed the instruction to connect the bot to my Mattermost instance and I'm facing 429 error from ChatGPT.
Any idea?
Thanks

**Comment by yGuy** [comment]
https://www.mlyearning.org/chat-gpt-error-429/

**Comment by yGuy** [comment]
Either way, it's not the bot that sends 429 but OpenAI, so the problem is not with the bot. Check with OpenAI to debug the problem.
