### ISSUE TITLE
Compatibility with llama and/or alpaca 

### ISSUE THREAD

**Issue by pums974** [yGuy/chatgpt-mattermost-bot#6]
Would it be possible?

**Comment by yGuy** [comment]
That would be possible, technically. Maybe I will try this. One problem is that the above LLMs come with a license that does not allow commercial use, so using an implementation other than for pure private research purposes needs to be considered, carefully.

**Comment by yGuy** [comment]
Hey, that was easier than I thought! I have this implemented in a separate branch and it works!

![image](https://user-images.githubusercontent.com/2486305/227724404-1a2e89e2-ad56-4c61-addb-0ce8024c6e37.png)

**Comment by pums974** [comment]
Awesome ! Thanks

**Comment by pums974** [comment]
I just tried it and indeed it's working perfectly fine.

thanks again
