### ISSUE TITLE
Enable finetuning of Assistant Role

### ISSUE THREAD

**Issue by m00nyONE** [yGuy/chatgpt-mattermost-bot#62]
it would be awesome if we would get the ability to customize the line here https://github.com/yGuy/chatgpt-mattermost-bot/blob/4cae8f96024bcde9cf7daa405695ab8244a528da/src/botservice.ts#L33 with our own. The easiest solution would be an Environment Variable to do this.
This would allow us to give the Bot more Identity. Our Employees usually ask ChatGPT coding questions or need assistance on writing in-code documentation. If we could  personalize the instruction message, this would be very helpfull.

**Comment by m00nyONE** [comment]
i will put together a PR later if interested

**Comment by yGuy** [comment]
I was going to give this task to some interns :-)   - but that might take a while. I am very busy myself, at the moment, unfortunately. A PR for this one should be easy to implement (and review). So, yes, thank you!

**Comment by yGuy** [comment]
merged into v2.3.0
