### ISSUE TITLE
specify custom URL for openai compatible APIs?

### ISSUE THREAD

**Issue by bozakov** [yGuy/chatgpt-mattermost-bot#67]
It would be great if it would it be possible to specify an environment variable for an alternative, openai compatible API. This would allow the use of locally hosted llm servers.
Would this be feasible?

Basically setting `basePath` to the `Configuration` in: https://github.com/yGuy/chatgpt-mattermost-bot/blob/c6e547125f7bfb24efe14ac990ee05dbac5d6564/src/openai-wrapper.ts#L16

**Comment by yGuy** [comment]
Yes, that could be helpful. It would be very easy to implement. I would be happy to merge a corresponding PR.

**Comment by bozakov** [comment]
Hi @yGuy any feedback on #68?

**Comment by yGuy** [comment]
This LGTM, thanks! I am currently swamped with work. Might be able to merge this at the weekend!

**Comment by yGuy** [comment]
merged in v2.2.0
